### ISSUE TITLE
Inference  구현 with 제주도 방언 데이터

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/dekorde#6]
## To-do's
- [x] 제주도 방언 데이터 push하기.
- [x] 한국어 형태소를 정수인코딩 &  토크나이징을 간편하게 할 수 있는 방법을 생각해보기.
- [x] inference에는 루프가 필요하다 -> 이걸 어떻게 구현할 수 있을까?
- [ ] inference에 어떤 문제가 있는지 파악하기!
- [ ] 패딩 마스크도 구현해야함 -> 이건 일단 나중에.

**Comment by eubinecto** [comment]
## 그럼 이 문제를 어떻게 해결해야하나?

패딩이 된 부분에 마스크를 추가해야한다. 
그런데 이 마스킹을 어떻게 진행을 해야할까?

### self-attention layer에다가.. padding mask를 추가해야한다.

lookahead 마스크와는 무엇이 다른가?

**Comment by ArtemisDicoTiar** [comment]
왜 인지 모르겠는데 `tokenembeddings.weight`의 shape이 30001, 64이다.
H_y가 10, 50인데...
64가 아니라 50이 나와야하는 게 아닌가..? ㅠ

**Comment by ohsuz** [comment]
50 = max_length, 64 = hidden_size 이니까 token_embeddings.weight의 크기는 (vocab size, hidden size) = (30001, 64)가 맞아용

H_y의 크기가 (bs, max_length, hidden_size) 여야 하는데 (10, 50)으로 찍히는 걸 보면 forward에서 잘못된 것 같은..!?

그리고 config에 batch size가 50인데 왜 10으로 찍히는지 보니까 데이터를 애초에 10개만 불러오네요! 데이터 개수를 늘려서 해보니까 mask 부분에서 에러가 납니다 마스크가.. 문제가 아닐지..?!
(RuntimeError: The size of tensor a (0) must match the size of tensor b (50) at non-singleton dimension 2)
